language: cpp
sudo: false
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libboost-dev
      - libcppunit-dev
      - libboost-test-dev
      - libgtest-dev
before_script:
    - "cd /usr/src/gtest && sudo cmake . && sudo make && sudo cmake --build . && sudo mv libgtest* /usr/lib/ ; cd -"
script:
  - make
