language: cpp
sudo: true
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libboost-dev
      - libcppunit-dev
      - libboost-test-dev
      - libgtest-dev
before_script:
    - "cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libg* /usr/lib/ && cd -"
script:
  - make
